#ifndef CERTIFICATE_H
#define CERTIFICATE_H

const char *root_ca =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIDoTCCA0igAwIBAgIRAO6Z9P1P3584De+0GaKWIIYwCgYIKoZIzj0EAwIwOzEL\n"
    "MAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczEMMAoG\n"
    "A1UEAxMDV0UxMB4XDTI0MDkxODEwMDAzM1oXDTI0MTIxNzEwMDAzMlowFTETMBEG\n"
    "A1UEAxMKbWxzYWZmLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLDPiVtX\n"
    "miRTng8Cbxad7xIliNcgSMHCX71hpwXXrKE2uiLMmTCVE3MKMv/OusB/6ogIejFq\n"
    "RfpPGmc6MHnCB1+jggJRMIICTTAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYI\n"
    "KwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUSl1kxnbOegcFEpWm+c3c\n"
    "33dccygwHwYDVR0jBBgwFoAUkHeSNWfE/6jMqeZ72YB5e8yT+TgwXgYIKwYBBQUH\n"
    "AQEEUjBQMCcGCCsGAQUFBzABhhtodHRwOi8vby5wa2kuZ29vZy9zL3dlMS83cGsw\n"
    "JQYIKwYBBQUHMAKGGWh0dHA6Ly9pLnBraS5nb29nL3dlMS5jcnQwIwYDVR0RBBww\n"
    "GoIKbWxzYWZmLmNvbYIMKi5tbHNhZmYuY29tMBMGA1UdIAQMMAowCAYGZ4EMAQIB\n"
    "MDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jLnBraS5nb29nL3dlMS9yZ2Vva1JB\n"
    "X24tZy5jcmwwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgB2/4g/Crb7lVHCYcz1\n"
    "h7o0tKTNuyncaEIKn+ZnTFo6dAAAAZIEyoTHAAAEAwBHMEUCIQDfWQ3wkU4kSMT3\n"
    "PQLoyJYBdVLCRyxi8tobnsfoD0E/WgIgf2eN8JBKnmfs7CJQT0HvAgAS9MFZuRWB\n"
    "7xyok4e/JRMAdgBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAZIE\n"
    "yoS1AAAEAwBHMEUCIEYnDwNJHjyNza8eY4yAQ/dzVpCE64cehLdzzWunEcGRAiEA\n"
    "7vKTK4YC9D8zqvyxH3g+JQbpsmy4ZA++bkQ2I3fkrW4wCgYIKoZIzj0EAwIDRwAw\n"
    "RAIgfXAMt44ZN8Iw/hqKHLTZedbrnzUkNHVhl1Kq+z/LekoCIBhqkpluvQCSCuY+\n"
    "BJCCTT76mMS7eDixnYsfPeUqNtqg\n"
    "-----END CERTIFICATE-----";

#endif
